[package]
name = "sqlite3dyn"
version = "0.1.2"
edition = "2024"
rust-version = "1.85.0"
author = ["jeppeter <jeppeter@gmail.com>"]
description = """
rust dynamic call sqlite3 share object
"""
license = "MIT/Apache-2.0"

repository = "https://github.com/jeppeter/sqlite3dyn-rs"


[dependencies]
libloading = "^0.9.0"
chrono = "^0.4.0"
lazy_static = "^1.4.0"
